version: 0.2

phases:
  install:
    commands:
      - echo "Creating 1GB file in Windows environment..."
  pre_build:
    commands:
      - echo "Creating 1GB file in Windows environment..."
  build:
    commands:
      - echo "Continue with build steps here..."
